### ISSUE TITLE
Compatibility with `aioboto3` >= 13.0

### ISSUE THREAD

**Issue by jmehnle** [phillipuniverse/pytest-aioboto3#4]
`pytest-aioboto3` currently depends on `aioboto3` `^12.0.0`. What stops it from running with `aioboto3` >=13.0? Can you please bump the dependency?

FWIW, the `aioboto3` changelog is here: https://github.com/terricain/aioboto3/blob/main/CHANGELOG.rst

**Comment by phillipuniverse** [comment]
Good point, no strong reason.

It would be nice to be able to add tox into here to make sure everything works with multiple versions of aioboto3, I would be happy to accept additional contributions towards that end.

With the very light touch that I maintain this project as it is, I think you're right that the correct answer is to pin the dependency as `>= 12.0.0` so other people can at least use it and report problems.

Thanks for opening an issue!

**Comment by phillipuniverse** [comment]
FYI I tagged 0.3.0 that relaxes the version constraint.

Thanks again for the report!
