### ISSUE TITLE
Is python>=3.10 restriction necessary?

### ISSUE THREAD

**Issue by Alexander-Serov** [phillipuniverse/pytest-aioboto3#8]
Hey!

For those of us back there on older python versions, I wanted to check with you whether the `python>=3.10` [restriction](https://github.com/phillipuniverse/pytest-aioboto3/blob/41a057ab9884603e8c65694096d839a54367f1fb/pyproject.toml#L12) is really necessary? I have had a short look through the code and it seemed to me that `python>=3.8` would work just fine, no?

Thanks

**Comment by phillipuniverse** [comment]
Not strictly necessary, I'm just personally not interested in maintaining < 3.10.

Feel free to fork and change the restriction!

**Comment by phillipuniverse** [comment]
Well TBH I can't just leave my other maintainer out to dry!!

**Comment by phillipuniverse** [comment]
Python 3.8 and 3.9 support is included in version 0.5.0!

**Comment by Alexander-Serov** [comment]
> Well I can't just leave my other maintainer out to dry!!

Oh, so sweet. 🤗
